apiVersion: apps/v1
kind: Deployment
metadata:
  name: swapy-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swapy-test
  template:
    metadata:
      labels:
        app: swapy-test
    spec:
      containers:
      - name: endpoint-app
        image: osacar93/prueba_final:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 800m
            memory: 512Mi
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
  strategy:    
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0        
         
