apiVersion: apps/v1
kind: Deployment
metadata:
  name: swapy-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swapy-test
  template:
    metadata:
      labels:
        app: swapy-test
    spec:
      containers:
      - name: endpoint-app
        image: osacar93/swapy-test:latest
        ports:
        - containerPort: 80