# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swapi-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swapi-microservice
  template:
    metadata:
      labels:
        app: swapi-microservice
    spec:
      containers:
      - name: swapi-microservice
        image: pr2-prv1/swapi-microservice:latest
        ports:
        - containerPort: 5000
