# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: swapi-microservice
spec:
  selector:
    app: swapi-microservice
  ports:
  - name: http
    port: 80
    targetPort: 5000
  type: LoadBalancer
