name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t osacar93/swapy-test:latest .
          docker push osacar93/swapy-test:latest

      - name: Deploy to Kubernetes
        uses: kubernetes/deploy-action@v1
        with:
          cluster: ${{ secrets.KUBECONFIG }}
          config: deploy.yml
