name: Deploy to Minikube

on:
  push:
    branches:
      - main
      - feature/change-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test de performance (opcional)
        run: |
          # Ejecutar test de performance para Python
          # (opcional, puedes comentar esta sección si no lo necesitas)
          #pip install locust
          #locust -f tests/performance_test.py --headless --num_users=10 --hatch_rate=1 
      - name: Verificar conexion a swapy.dev
        run: |
          # verificar conexion con curl
          curl https://swapi.dev                 
      - name: Desplegar en Minikube
        run: |
          # Instalar Minikube
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

          # Iniciar Minikube
          minikube start --driver=docker --v=5

          #comprobar directorio actual 
          pwd
          ls -l


          # Desplegar en Minikube
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          kubectl apply -f data-pvc.yaml

          kubectl rollout status deployment/swapy-deploy
          kubectl get pods

          # Verificar el estado del deployment
          kubectl get deployments

          # Consultar logs de un pod para sacar json de /people 
          kubectl logs $(kubectl get pods -o jsonpath='{.items[0].metadata.name}')

      - name: Verificar contenido de people.json
        run: |
          kubectl exec -it $(kubectl get pods -o jsonpath='{.items[0].metadata.name}') -- cat people.json          


