name: Deploy to Minikube

on:
  push:
    branches:
      - main
      - feature/change-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verificar conexion a swapy.dev
        run: |
          # verificar conexion con curl
          curl https://swapi.dev    
          
      - name: Verificar contenido del directorio actual
        run: |
          ls -l    

      - name: Desplegar en Minikube
        run: |
          # Instalar Minikube
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

          # Iniciar Minikube
          minikube start --driver=docker --v=5

          # Desplegar en Minikube
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          #kubectl apply -f data-pvc.yaml

          kubectl rollout status deployment/swapy-deploy

          # Verificar el estado del deployment
          kubectl get deployments

      - name: Listar pods disponibles
        run: |
          kubectl get pods 

          # Consultar logs de un pod 
          kubectl logs $(kubectl get pods -o jsonpath='{.items[0].metadata.name}')

      - name: Verificar contenido de people.json
        run: |
          kubectl exec -it $(kubectl get pods -o jsonpath='{.items[0].metadata.name}') -- cat people.json

        
      - name: Test de performance (opcional)
        run: |
          # Ejecutar test de performance para Python
          # (opcional, puedes comentar esta sección si no lo necesitas)

          kubectl exec -it $(kubectl get pods -o jsonpath='{.items[0].metadata.name}') -- pip update locust
          kubectl exec -it $(kubectl get pods -o jsonpath='{.items[0].metadata.name}') -- locust -f performance_test.py  --headless --host="http://localhost:5000" --run-time=10s


