name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/swapi-microservice:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/swapi-microservice:latest

      - name: Deploy to Kubernetes
        uses: kubernetes/deploy-action@v1
        with:
          cluster: <tu-cluster-de-kubernetes>
          namespace: default
          deployment: swapi-microservice
          image: ${{ secrets.DOCKER_USERNAME }}/swapi-microservice:latest
